language: go

go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"
  - "1.13"
  - tip

install:
  - make build-libgit2-static
  - go get --tags "static" ./...

script:
  - make test-static

matrix:
  allow_failures:
    - go: tip

git:
  submodules: true

branches:
  only:
  - master
  - /v\d+/
  - /release-.*/
