language: go

install:
  - cd "${HOME}"
  - wget -O libgit2-0.22.1.tar.gz https://github.com/libgit2/libgit2/archive/v0.22.1.tar.gz
  - tar -xzvf libgit2-0.22.1.tar.gz
  - cd libgit2-0.22.1 && mkdir build && cd build
  - cmake -DTHREADSAFE=ON -DBUILD_CLAR=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DCMAKE_INSTALL_PREFIX=/usr/local .. && make && sudo make install
  - sudo ldconfig
  - cd "${TRAVIS_BUILD_DIR}"

go:
  - 1.1
  - 1.2
  - 1.3
  - tip

matrix:
  allow_failures:
    - go: tip
